---
- name: Web Site Checks Rulebook
  hosts: all
  
  sources:
    - name: Are my key web sites operational
      ansible.eda.url_check:
        verify_ssl: false
        delay: 30 # seconds
        urls:
          - https://status.redhat.com
          - http://loadofrubbishurl.com
        
  rules:
    - name: "Alert if URL is down (call AAP controller)"
      condition: event.url_check.status == "down"
      throttle:
        once_within: 5 minutes
        group_by_attributes:
          - event.meta.urls
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
