---
- name: Web Site Checks Rulebook
  hosts: all
  
  sources:
    - name: Are my key web sites operational
      ansible.eda.url_check:
        verify_ssl: false
        delay: 30 # seconds
        urls:
          - https://status.redhat.com:wq
          - http://loadofrubbishurl.com
#
# How to easily debug output (to get event metadata for instance)
#
#  rules:
#    - name: Debug output
#      condition: event.url_check.status == "down"
#      action:
#        debug:

  rules:
    - name: "Alert if URL is down (call AAP controller)"
      condition: event.url_check.status == "down"
      throttle:
        once_within: 5 minutes
        group_by_attributes:
          - event.meta.url_check.url
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
